language: go
go:
- 1.11.x
script:
- go vet ./...
- go test ./...
notifications:
  slack:
    secure: FCV30iYUUaudgw/K+cZO6FL4amoe5c+GiWh3LxMWgGtXBd9QVZGlB71U04qsvNRT2ovNrfIzYj9HLJhftsaE4gLl29vzkd9tgVI/9klAvo7QqE7sOw/wj8aTh6Mklfq2aIwDArkhb0AcZuLL5sPYzKRajqcAMPo6ip+ugMVs0MRkEXJfET3JP8+PbT6HNMS8FH4Bk/T4pegHAMfnFzRLKFLJMhioG2VDpkffDfYRo8+ZrxGtBfPyPNHrVePKYgq4tak4mMH0kPZlWfhN5hVRYKBtyfs9v1JdJb6JSocmdbcpW2gQB97z4vlCcHZl9xx3dw8T+/LI1VWorukysxE/Pe4ldPmOEAs7jy2TchMmy4+W2DdWJyjj6DkukgI6WM6Pss3X8pj4NzZfG/nhz6Bxgi+E/K6JBG8Oh/i18WmjRUAJnRxmcCAJ1kSf/52asHe5TfvuLn5LmAILtLlsVpENK+ox1DMzSBDXXFwDqYvX60eGK1TYa4VCbyTStMJ2ruYukQesmfDyj/aIThMvw8qxnzkD7DkKw+2TLmk1AgMFPcZQI3DzuuZSKRVLVck01yEM/d0apQTDFEBdcf3D0swz2Mcy5X1+vW4lA3UuLczp4XloD9kpYQHJIsH/7sCQjO1gmzpLz1YS35RtLa8FrwMGuoSK5wLNFAPnzjw4rgKp+Hk=
deploy:
  provider: heroku
  api_key:
    secure: baM1QeD5Pg77ZLMeYY8B523rOO7+hmbAOMQppue/tGX1+55jpdBoUbSQMlyMxxXsvLkvxV7LqDCL/UdGjNWRie1LeikTT2nDN+8qfvq31Kj9HUP/vIxm9k+U/wFk3NvpuXWbWgU9pqj0fleHTEmDn7+L7SieoI4TGdzQbgdglo2NBP8ZPBk9aMXORruXcMHuNDyOrgFUmVsIyx9wx3fm9/dWjWkz7AAI/k15Tw4H1EkBpgM2vzDKwZBGR6QBZGEitqJjDGCy2X9AKyl9/y+arJX8H16naYcBNPpcdLAB57Zp7/A075U3CpoJ05Tfh8or0lqEob8z3KcGoIPxfmVfF1OWPomxMCk1KQ+jnlAgZ7iu/X5lxWDNnh7HQMLvF8TR3wEh8fow6TUqkae/4Ik1zt5HB7GjLBgQsoMRNfAyQKtxMnJj0G6XwdLJmEVBC3yo4CBoBbTBUXj0sfs72JJciHdnl17nb4Xph8AjhXiF0YDFZh1SOne7ig58SBi4hlKqup40Bg4CgBaZtKQlZLO9cQiJQbCy2QPqnzrIoOEYBDhySMSEgaRRiaO/umxSH+z1qNKc9oEle4afAK6aEtv4rR51DeM9KZEGSnd3qwIE8Z5AIUvylKSRFRh4rSSDZwE6OaFnO3lNhdJgxqmK16UQVAtX0YhuTglBwG2PlyCNjro=
