language: go
go:
- 1.11.x
script:
  - go vet ./...
  - go test ./...
notifications:
  slack:
    secure: FCV30iYUUaudgw/K+cZO6FL4amoe5c+GiWh3LxMWgGtXBd9QVZGlB71U04qsvNRT2ovNrfIzYj9HLJhftsaE4gLl29vzkd9tgVI/9klAvo7QqE7sOw/wj8aTh6Mklfq2aIwDArkhb0AcZuLL5sPYzKRajqcAMPo6ip+ugMVs0MRkEXJfET3JP8+PbT6HNMS8FH4Bk/T4pegHAMfnFzRLKFLJMhioG2VDpkffDfYRo8+ZrxGtBfPyPNHrVePKYgq4tak4mMH0kPZlWfhN5hVRYKBtyfs9v1JdJb6JSocmdbcpW2gQB97z4vlCcHZl9xx3dw8T+/LI1VWorukysxE/Pe4ldPmOEAs7jy2TchMmy4+W2DdWJyjj6DkukgI6WM6Pss3X8pj4NzZfG/nhz6Bxgi+E/K6JBG8Oh/i18WmjRUAJnRxmcCAJ1kSf/52asHe5TfvuLn5LmAILtLlsVpENK+ox1DMzSBDXXFwDqYvX60eGK1TYa4VCbyTStMJ2ruYukQesmfDyj/aIThMvw8qxnzkD7DkKw+2TLmk1AgMFPcZQI3DzuuZSKRVLVck01yEM/d0apQTDFEBdcf3D0swz2Mcy5X1+vW4lA3UuLczp4XloD9kpYQHJIsH/7sCQjO1gmzpLz1YS35RtLa8FrwMGuoSK5wLNFAPnzjw4rgKp+Hk=
deploy:
  provider: heroku
  api_key:
    secure: jmf+vuQGEuFZQyK0QyZG5nCLZwWHznKrE8FliKp+2pVvKeWmSi5wIf1pUaO+e3FArfmG5EOqmeYcTEqAvQvIk+HveXs1AGbu7Gs8zavBBHqjHLM7EA3GVabW10zJyZ/lyT5H8cPC2dbYqhYjJIuJDs5KGewddOqewkiDsDtKWKWLyAGFfzM+o25BpC2Sj2KRBVJXy2U1E3rkRPv94TZZ0JXqg1ZYl4wbCLb/OhOIT+Sku+YOsYvMqsvtnufRe6+s+kOP93gR3uVVqFjj56DTdUsKOI2+CqMwWAsIJgrPEkMSgxZOjp5oYxvlHgkFaqwdbCl9gqql0XEO116Vo53bR/FzKfyL8ZSfn8ln8Ais3d28amNKcDNZ/tGWQEHTgm+chstaqS4DCuTmxv5wVPEpKrwrUk/BqOQCCfcuCp74514CxApKf+SbNyp5vKktILCs97GSzH/let4WyT4rYYSES+rklUUZZL8fukjod/2unEs3QjnKYIGK3hsvswrc1rzdV+btGi1g00iWZsdnZ7qdMAVL9Xo1NdsEgRZLqo5Q+cKAgXl35/MLTbMBxckm3X6Y810GluVRCqBHYEsICDnrmNjxqRCw8HlTDGkbORrY84QLEIdwwL7rWIY2uaCYoDunmsmPiHltSVaPkz5tW68wgH2i2jRbwsAPO9HXvdr34ak=
